# GitHub App Configuration
# This file documents the required GitHub App settings
# Update these manually at: https://github.com/settings/apps/greener-cicd-app

app:
  name: "Greener CI/CD App"
  description: "Automated CI/CD operations for private projects with intelligent secret management"

  # URLs
  homepage_url: "https://github.com/greener-hayden/dotfiles"
  callback_url: ""  # Not needed for CI/CD operations
  setup_url: "https://github.com/greener-hayden/dotfiles/blob/main/github-app/SIMPLE_SETUP.md"

  # Features
  redirect_on_update: true
  request_oauth_on_install: false
  device_flow_enabled: false

  # Webhook (only needed if using webhook approach)
  webhook:
    active: false  # Set to true only if using webhook handler
    url: ""  # Not needed for GitHub Actions approach
    secret: ""  # Store in secrets, not here

# Permissions required
permissions:
  # Repository permissions
  actions: write          # Manage GitHub Actions
  contents: read          # Read repository contents
  metadata: read          # Read repository metadata
  secrets: write          # Manage repository secrets

  # Organization permissions (optional)
  organization_secrets: write  # If managing org-wide secrets

# Events (only if webhook is active)
events:
  - installation
  - installation_repositories

# Private key info (for reference only - DO NOT STORE KEY HERE)
private_key:
  fingerprint: "SHA256:IM46gNEGPzDB+TI2G5eXCM6ixVTiUq3mhIdNLWBPWRc="
  added_date: "2024-01-14"
  added_by: "greener-hayden"

# Client secret info (for OAuth - not used in CI/CD)
client_secret:
  last_4: "f69c4f08"
  usage: "Not required for CI/CD automation"
  note: "GitHub requires at least one client secret to exist"

# Installation info
installation:
  id: 85948928
  account: "greener-hayden"
  type: "user"  # or "organization"