# GitHub App Manifest for Greener CI/CD App
# This file defines the configuration for your GitHub App
# Use this to create/update your app at https://github.com/settings/apps

name: Greener CI/CD App
description: Automated CI/CD integration for greener-hayden repositories
url: https://github.com/greener-hayden/dotfiles
hook_attributes:
  url: https://your-webhook-handler.com/webhooks/github
  active: true

# Permissions required by the app
default_permissions:
  # Repository permissions
  actions: write           # Manage GitHub Actions workflows and runs
  contents: read           # Read repository contents
  metadata: read           # Read repository metadata
  pull_requests: write     # Create and manage pull requests
  issues: write           # Create and manage issues
  checks: write           # Create and manage check runs
  secrets: write          # Manage repository secrets (crucial for CI/CD)
  environments: write     # Manage deployment environments
  administration: read    # Read repository settings

  # Organization permissions (if installing on org)
  organization_administration: read
  organization_secrets: write

# Events the app subscribes to
default_events:
  - installation           # When app is installed/uninstalled
  - installation_repositories  # When repos are added/removed
  - push                  # Code push events
  - pull_request          # PR events
  - workflow_run          # Workflow execution events
  - workflow_job          # Workflow job events
  - repository            # Repository created/deleted
  - release              # Release events
  - deployment           # Deployment events
  - deployment_status    # Deployment status updates

# App settings
public: false              # Private app for your use
webhook_secret: required   # Will be generated during creation

# Installation settings
setup_url: https://github.com/greener-hayden/dotfiles/blob/main/github-app/SETUP.md
setup_on_update: true

# Callback URL for OAuth (if needed)
callback_url: https://your-domain.com/auth/callback

# Required for GitHub Actions integration
request_oauth_on_install: false
request_oauth_on_update: false