name: Reusable Optimized Workflow

on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner to use'
        type: string
        default: 'ubuntu-22.04'
      timeout:
        description: 'Timeout in minutes'
        type: number
        default: 1
      skip-on-ci:
        description: 'Skip on [skip ci] commits'
        type: boolean
        default: true

jobs:
  check-skip:
    if: inputs.skip-on-ci && !contains(github.event.head_commit.message, '[skip ci]')
    runs-on: ubuntu-22.04
    timeout-minutes: 1
    outputs:
      should-run: ${{ steps.check.outputs.run }}
    steps:
      - id: check
        run: echo "run=true" >> $GITHUB_OUTPUT

  # Shared caching configuration
  cache-setup:
    runs-on: ${{ inputs.runner }}
    timeout-minutes: ${{ inputs.timeout }}
    steps:
      - name: Cache GitHub CLI
        uses: actions/cache@v4
        with:
          path: |
            ~/.local/bin/gh
            ~/.config/gh
          key: gh-cli-${{ runner.os }}
          restore-keys: gh-cli-

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache
            ~/.npm
            ~/.local
          key: deps-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/requirements.txt') }}
          restore-keys: |
            deps-${{ runner.os }}-
            deps-