name: Test Local with act

on:
  workflow_dispatch:
  push:
    branches: [test-*]

jobs:
  test-performance:
    runs-on: ubuntu-22.04
    timeout-minutes: 1

    steps:
      - name: Start timer
        id: timer
        run: echo "start=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Minimal checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
          sparse-checkout-cone-mode: false

      - name: Simulate API calls
        run: |
          # Simulate fast API responses
          echo "Mock: Getting installations..."
          sleep 0.1

          echo "Mock: Processing 10 repos..."
          for i in {1..10}; do
            echo "  Repo $i: ✓"
          done

      - name: Calculate runtime
        run: |
          START=${{ steps.timer.outputs.start }}
          END=$(date +%s)
          RUNTIME=$((END - START))

          echo "### Performance Test" >> $GITHUB_STEP_SUMMARY
          echo "- Runtime: ${RUNTIME}s" >> $GITHUB_STEP_SUMMARY
          echo "- Repos: 10 (mock)" >> $GITHUB_STEP_SUMMARY
          echo "- Per repo: $((RUNTIME * 100 / 10))ms" >> $GITHUB_STEP_SUMMARY